# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-53-vote-change-rats-to-pickles-c124c68
redis:
  usePassword: false
replicaCount: 1
