# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-18-change-mice-to-dogs-ce4e1af
redis:
  usePassword: false
replicaCount: 1
