# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-22-update-birds-to-dogs-b03c7fc
redis:
  usePassword: false
replicaCount: 1
