# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
  tag: pr-100-random-vote-change-42-0f91707
redis:
  usePassword: false
replicaCount: 1
