# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-14-update-cats-to-lizards-43ae64f
redis:
  usePassword: false
replicaCount: 1
