# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-65-random-vote-change-7-2b8adb1
redis:
  usePassword: false
replicaCount: 1
