# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-50-vote-cats-vs-rats-a941e01
redis:
  usePassword: false
replicaCount: 1
