# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-59-random-vote-change-1-ba8008c
redis:
  usePassword: false
replicaCount: 1
