# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
  tag: pr-104-random-vote-change-46-a93b6d4
redis:
  usePassword: false
replicaCount: 1
