# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-16-update-lizards-to-mice-83b9077
redis:
  usePassword: false
replicaCount: 1
