# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-58-vote-dogs-to-pickles-eee5a9c
redis:
  usePassword: false
replicaCount: 1
