# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-60-random-vote-change-2-a262bba
redis:
  usePassword: false
replicaCount: 1
