# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-63-random-vote-change-5-fd2606a
redis:
  usePassword: false
replicaCount: 1
