# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-17-update-snakes-to-cats-658ffc1
redis:
  usePassword: false
replicaCount: 1
