# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-64-random-vote-change-6-8c7c209
redis:
  usePassword: false
replicaCount: 1
