# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-19-update-cats-to-birds-71f299d
redis:
  usePassword: false
replicaCount: 1
