# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-3-update-services-update-cats-to-squirrels-7e6657d
redis:
  usePassword: false
replicaCount: 1
