# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-66-random-vote-change-8-5ae360d
redis:
  usePassword: false
replicaCount: 1
