# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-39-change-dog-to-bird-vote-app-cbce02c
redis:
  usePassword: false
replicaCount: 1
