# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/vote
  tag: pr-47-vote-cats-vs-pickles-03882ae
redis:
  usePassword: false
replicaCount: 1
