result:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/result
    tag: stable
vote:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
    tag: stable
worker:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
    tag: stable
