result:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/result
    tag: pr-129-fix-result-restarts-05e7d9b
vote:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
    tag: pr-86-random-vote-change-28-7a550fd
worker:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
    tag: stable
