result:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/result
    tag: pr-135-random-result-change-26-a57de41
vote:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
    tag: pr-86-random-vote-change-28-7a550fd
worker:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
    tag: stable

postgresql:
  enabled: true
  auth:
# copied over from ../../values.yaml
    postgresPassword: <path:kv/data/postgres#password>

# copied over from ../../values.yaml
redis:
  enabled: true
  auth: 
    enabled: false
