result:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/result
    tag: ${{RELEASE_CANDIDATE_IMAGE_TAG}}
vote:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
    tag: pr-86-random-vote-change-28-7a550fd
worker:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
    tag: stable
postgresql:
  auth:
    postgresPassword: <path:kv/data/postgres#password>
