result:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/result
    tag: "pr-11-update-hamsters-to-birds-4b53f55"
vote:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
    tag: "pr-11-update-hamsters-to-birds-4b53f55"
worker:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
    tag: stable
