version: '1.0'

stages:
  - clone
  - fetch_candidate
  - promote_candidate

steps:
  clone_source_repo:
    title: Cloning Source Repository
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{TARGET_REPO}}
    revision: main
    stage: clone

  determine_candidate_source:
    title: Determining Candidate Source
    type: freestyle
    image: quay.io/codefresh/cli
    shell: bash
    commands:
      - |-
        if [ "$SOURCE_FILE" ] ; then
            cf_export CANDIDATE_SOURCE=$SOURCE_FILE
        else
            cf_export CANDIDATE_IMAGE_TAG=$(echo "$CF_PULL_REQUEST_HEAD_BRANCH-$CF_PULL_REQUEST_HEAD_COMMIT_SHA" | awk '{print tolower($0)}')
        fi
    stage: fetch_candidate

  fetch_candidate:
    title: Fetch Release Candidate
    type: freestyle
    image: quay.io/codefresh/cli
    working_directory: ${{clone_target_repo}}
    commands:
      - cf_export CANDIDATE_IMAGE_TAG=$(codefresh get annotation build ${{CF_BUILD_ID}} candidate_image_tag -o json | jq -r '.value')
    stage: promote_candidate

  update_target_environment:
    title: Update Target Environment
    type: freestyle
    image: mikefarah/yq:4
    working_directory: ${{clone_target_repo}}
    commands:
      - echo "Before Changes"
      - cat ${{TARGET_FILE}}
      - yq -i '${{TARGET_FILE_IMAGE_TAG_PLACEMENT}} = "${{CANDIDATE_IMAGE_TAG}}"' ${{TARGET_FILE}}
      - echo "After Changes"
      - cat ${{TARGET_FILE}}
    stage: promote_candidate

  commit_and_push:
    title: Commit manifest
    type: git-commit
    arguments:
      repo: ${{CF_REPO_OWNER}}/${{TARGET_REPO}}
      git: salesdemocf
      working_directory: '/codefresh/volume/${{TARGET_REPO}}'
      commit_message: Committed Promotion Candidate ${{CANDIDATE_IMAGE_TAG}} to ${{TARGET_FILE}}
      git_user_name: salesdemocf
      git_user_email: salesdemocf@gmail.com
      rebase: true
    stage: promote_candidate
