version: '1.0'

stages:
  - clone
  - propose
  - approve
  - promote

steps:
  clone_source_repo:
    title: Cloning Source Repository
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: main
    stage: clone

  clone_target_repo:
    title: Cloning Target Repository
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{TARGET_REPO}}
    revision: main
    stage: clone
    when:
      condition:
        all:
          SourceRepoNotTargetRepo: 'includes("${{CF_REPO_NAME}}", "${{TARGET_REPO}}") == false'

  environment_change_proposal:
    title: Update Target Environment
    type: freestyle
    image: mikefarah/yq:4
    commands:
      - echo "Environment Before Changes"
      - cat ${{CF_VOLUME_PATH}}/${{TARGET_REPO}}/${{TARGET_FILE_PATH}}/${{TARGET_FILE}}
      - yes | cp -rf ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/${{SOURCE_FILE_PATH}}/${{SOURCE_FILE}} ${{CF_VOLUME_PATH}}/${{TARGET_REPO}}/${{TARGET_FILE_PATH}}/${{TARGET_FILE}}
      - echo "Environment After Changes"
      - cat ${{CF_VOLUME_PATH}}/${{TARGET_REPO}}/${{TARGET_FILE_PATH}}/${{TARGET_FILE}}
    stage: propose

  wait_for_approval:
    title: Review Candidate Report and Approve Update Plan for Release.
    type: pending-approval
    stage: approve

  commit_and_push:
    title: Commit manifest
    type: git-commit
    arguments:
      repo: ${{CF_REPO_OWNER}}/${{TARGET_REPO}}
      git: salesdemocf
      working_directory: '/codefresh/volume/${{TARGET_REPO}}'
      commit_message: Promote ${{SOURCE_FILE_PATH}}/${{SOURCE_FILE}} to ${{TARGET_FILE_PATH}}/${{TARGET_FILE}}
      git_user_name: salesdemocf
      git_user_email: salesdemocf@gmail.com
      rebase: true
    stage: promote
