version: '1.0'

stages:
  - approve
  - clone
  - fetch_candidate
  - promote_candidate

steps:
  start_gitops_deployment:
    title: Would you like to start a GitOps Deployment?
    type: pending-approval
    stage: approve

  clone_source_repo:
    title: Cloning Source Repository
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: main
    stage: clone

  fetch_candidate:
    title: Identifying Release Candidate Details...
    image: alpine
    commands:
      - cf_export RELEASE_CANDIDATE_SERVICE=${{MICROSERVICE}}
      - cf_export RELEASE_CANDIDATE_IMAGE_TAG=pr-${{CF_PULL_REQUEST_NUMBER}}-${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    stage: fetch_candidate

  clone_target_repo:
    title: Cloning Source Repository
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{TARGET_REPO}}
    revision: main
    stage: clone

  update_target_environment:
    title: Update Target Environment
    type: freestyle
    image: mikefarah/yq:4
    working_directory: ${{clone_target_repo}}
    commands:
      - echo "Before Changes"
      - cat ${{TARGET_FILE}}
      - yq -i '${{TARGET_FILE_IMAGE_TAG_PLACEMENT}} = "${{RELEASE_CANDIDATE_IMAGE_TAG}}"' ${{TARGET_FILE}}
      - echo "After Changes"
      - cat ${{TARGET_FILE}}
    stage: promote_candidate

  commit_and_push:
    title: Commit manifest
    type: git-commit
    arguments:
      repo: ${{CF_REPO_OWNER}}/${{TARGET_REPO}}
      git: salesdemocf
      working_directory: '/codefresh/volume/${{TARGET_REPO}}'
      commit_message: Committed ${{MICROSERVICE}} Promotion Candidate ${{RELEASE_CANDIDATE_IMAGE_TAG}} to ${{TARGET_FILE}}
      git_user_name: salesdemocf
      git_user_email: salesdemocf@gmail.com
      rebase: true
    stage: promote_candidate
