apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eva-development
  annotations:
    codefresh.io/product: example-voting-app
spec:
  project: default
  sources:
    - chart: example-voting-app
      repoURL: https://codedev.jfrog.io/artifactory/api/helm/poc-demo-1-helm-local
      targetRevision: 1.1.12
      helm:
      valueFiles:
        - $values/environments/development/values.yaml
    - repoURL: https://github.com/salesdemocf/poc-demo-1-demo-app.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
