apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eva-staging
  annotations:
    codefresh.io/product: example-voting-app
spec:
  project: default
  sources:
    - repoURL: https://github.com/salesdemocf/poc-demo-1-demo-app.git
      targetRevision: HEAD
      path: example-voting-app
      helm:
        valueFiles:
          - $environments/eva/gitops/staging/values.yaml
    - repoURL: https://github.com/salesdemocf/poc-demo-1-environments.git
      targetRevision: HEAD
      ref: environments
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
