apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.image.tag | quote }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{default "Always" .Values.image.pullPolicy}}
        ports:
          - containerPort: 80
            name: http
        env:
        - name: REDIS_HOST
          value: {{ .Values.redis.host | default (printf "%s-redis-master" ( .Release.Name )) | quote }}
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: {{ template "fullname" . }}
      previewService: {{ template "fullname" . }}-preview
      metrics:
        - name: curl-{{ template "fullname" . }}
          provider:
            job:
              metadata:
                labels:
                  app: {{ template "fullname" . }}
                  chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
                  release: {{ .Release.Name  | quote }}
                  heritage: {{ .Release.Service  | quote }}
                  version: {{ .Values.image.tag | quote }}
              spec:
                backoffLimit: 1
                template:
                  spec:
                    containers:
                    - name: curl-{{ template "fullname" . }}
                      image: curlimages/curl:latest
                      command:
                        - /bin/sh
                        - -c
                        - |
                          curl -I https://www.baidu.com
                          status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "http://{{ template "fullname" . }}-preview.{{ .Release.Namespace  | quote }}.svc.cluster.local");
                          [ $status_code -eq 200 ]
                    restartPolicy: Never
      trafficRouting:
        alb:
          ingress: {{ template "fullname" . }}
          servicePort: 80